# ===============================================================
# ðŸ§¬ CoWERA Simulation Input File
# ---------------------------------------------------------------
# Define all parameters for your simulation run here.
# To launch:  python run_cowera.py --config input.yaml
# ===============================================================

# It needs to run on a gpu system . It is advised to run with cuda MPS enabled to speed up
#To enable cuda MPS paste the following commands in your terminal: set percentage acording to capacity
# nvidia-cuda-mps-control -d
# export CUDA_MPS_ACTIVE_THREAD_PERCENTAGE=20


# -------------------- System Information -------------------- #
# The system name and the full path to its directory.
# The directory should contain: .gro, .top, .itp, and other files.
system: "chignolin"
dir: "./Systems/chignolin" # make sure this directory has the system.py file which sets up the simulation and all other structure files

# -------------------- Simulation Setup ---------------------- #
# Number of parallel trajectories ("walkers").
num_walkers: 16

#maximum allowed probability for a walker
pmax: 0.20

# Run label (used in output folder names and log files).
run: "test_0"

# Number of MD steps between resamplings.
n_steps: 1000

# Total number of resampling cycles to perform.
n_cycles: 10000

# -------------------- Input / Output Files ------------------ #
# Starting structure file (.gro)
start: "chignolin_unfolded.pdb"

# Topology file for the system.
topol: "chignolin.prmtop"

# Target structure file (folded state reference) may be none if it corresponds to final folded or unfolded structures if feat = best_hummer_q.
target: "chignolin_folded.pdb"

# file used as the native may be none if sel_feat = rmsd_backbone.
native: "chignolin_folded.pdb"

# -------------------- Feature Selection --------------------- #
# Feature to monitor during simulation.
# Options: "best_hummer_q" (native contacts) or "rmsd_backbone".
sel_feat: "rmsd_backbone"

#select mode ("greedy" or "probabilistic")
mode: "probabilistic"

#select the metric for distance computation ("pairwise_rmsd" or "euclidean")
distance_criterion: "euclidean"

# -------------------- Distance Thresholds ------------------- #
# Merge cutoff distance (for resampling).
d_merge: 0.1

# Warped cutoff distance (for boundary condition)
d_warped: 0.05

# -------------------- Thermodynamic Settings ---------------- #
# Simulation temperature in Kelvin.
temp: 275.0

# -------------------- GPU Configuration --------------------- #
# GPU device IDs to use for CUDA execution.
# Repeat IDs if using NVIDIA MPS (multi-process service).
gpu_ids: [0, 0, 0, 0, 0]

# -------------------- Data Collection ----------------------- #
# Frequency (in steps) to save data during simulation.
save_freq: 100

# Number of bins for progress coordinate tracking.
n_bins: 29

# Maximum number of bins (usually same as n_bins or number of native contacts).
max_bins: 29

# -------------------- Folding / Unfolding Mode -------------- #
increment: -1

# -------------------- Output Configuration ------------------ #
# Name of subdirectory to store simulation results inside DIR.
output_folder: "folding_runs"
