name: cowera
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - ca-certificates=2025.8.3=hbd8a1cb_0
  - certifi=2024.8.30=pyhd8ed1ab_0
  - cudatoolkit=11.7.0=hd8887f6_10
  - fftw=3.3.10=nompi_h77c792f_102
  - ld_impl_linux-64=2.40=h12ee557_0
  - libblas=3.9.0=31_h59b9bed_openblas
  - libcblas=3.9.0=31_he106b2a_openblas
  - libffi=3.3=he6710b0_2
  - libgcc-ng=11.2.0=h1234567_1
  - libgfortran-ng=13.2.0=h69a702a_0
  - libgfortran5=13.2.0=ha4646dd_0
  - libgomp=11.2.0=h1234567_1
  - liblapack=3.9.0=31_h7ac8fdf_openblas
  - libopenblas=0.3.29=ha39b09d_0
  - libstdcxx-ng=11.2.0=h1234567_1
  - libxcb=1.17.0=h9b100fa_0
  - ncurses=6.5=h7934f7d_0
  - ocl-icd=2.3.1=h7f98852_0
  - ocl-icd-system=1.0.0=1
  - openmm=7.5.1=py37h96c4ddf_1
  - openssl=1.1.1w=h7f8727e_0
  - pip=21.2.2=py37h06a4308_0
  - pthread-stubs=0.3=h0ce48e5_1
  - python=3.7.13=haa1d7c7_1
  - python_abi=3.7=2_cp37m
  - readline=8.3=hc2a1206_0
  - sqlite=3.50.2=hb25bd0a_1
  - tk=8.6.15=h54e0aa7_0
  - wheel=0.37.1=pyhd3eb1b0_0
  - xorg-libx11=1.8.12=h9b100fa_1
  - xorg-libxau=1.0.12=h9b100fa_0
  - xorg-libxdmcp=1.1.5=h9b100fa_0
  - xorg-xorgproto=2024.1=h5eee18b_1
  - xz=5.6.4=h5eee18b_1
  - zlib=1.2.13=h5eee18b_1
  - pip:
      - anyio==3.7.1
      - argon2-cffi==23.1.0
      - argon2-cffi-bindings==21.2.0
      - astunparse==1.6.3
      - attrs==24.2.0
      - backcall==0.2.0
      - backports-functools-lru-cache==1.6.4
      - beautifulsoup4==4.13.5
      - biopython==1.81
      - bleach==6.0.0
      - boltons==23.0.0
      - bottleneck==1.3.5
      - cffi==1.15.1
      - click==8.1.7
      - cloudpickle==2.2.1
      - colorama==0.4.6
      - cycler==0.11.0
      - dask==2022.2.0
      - debugpy==1.7.0
      - decorator==5.1.1
      - deeptime==0.4.3
      - defusedxml==0.7.1
      - dill==0.3.7
      - eliot==1.14.0
      - entrypoints==0.4
      - exceptiongroup==1.3.0
      - fastjsonschema==2.21.2
      - fonttools==4.25.0
      - fsspec==2023.1.0
      - geomm==0.2.1
      - griddataformats==0.7.0
      - gsd==3.2.1
      - h5py==3.8.0
      - idna==3.10
      - importlib-metadata==6.7.0
      - importlib-resources==5.12.0
      - ipdb==0.13.13
      - ipykernel==6.16.2
      - ipython==7.31.1
      - ipython-genutils==0.2.0
      - jedi==0.18.1
      - jinja2==3.1.2
      - joblib==1.3.2
      - jsonschema==4.17.3
      - jupyter-client==7.4.9
      - jupyter-core==4.12.0
      - jupyter-server==1.24.0
      - jupyterlab-pygments==0.2.2
      - kiwisolver==1.4.2
      - llvmlite==0.39.1
      - locket==1.0.0
      - markupsafe==2.1.3
      - matplotlib==3.5.1
      - matplotlib-inline==0.1.6
      - mdanalysis==2.0.0
      - mdtraj==1.9.9
      - mistune==3.0.2
      - mmtf-python==1.1.3
      - mrcfile==1.5.4
      - msgpack==1.0.5
      - multiprocess==0.70.15
      - multiprocessing-logging==0.3.4
      - munkres==1.1.4
      - nbclassic==1.2.0
      - nbclient==0.7.4
      - nbconvert==7.6.0
      - nbformat==5.8.0
      - nest-asyncio==1.6.0
      - networkx==2.3
      - notebook==6.5.7
      - notebook-shim==0.2.4
      - numba==0.56.4
      - numexpr==2.8.3
      - numpy==1.21.5
      - openmm-systems==0.0.0
      - packaging==21.3
      - pandas==1.3.5
      - pandocfilters==1.5.1
      - parmed==4.0.0
      - parso==0.8.3
      - partd==1.4.0
      - pathos==0.3.1
      - pexpect==4.8.0
      - pickleshare==0.7.5
      - pillow==9.0.1
      - pint==0.18
      - pkgutil-resolve-name==1.3.10
      - ply==3.11
      - pox==0.3.3
      - ppft==1.7.6.7
      - prometheus-client==0.17.1
      - prompt-toolkit==3.0.36
      - psutil==5.9.7
      - ptyprocess==0.7.0
      - pycparser==2.21
      - pyemma==2.5.12
      - pygments==2.11.2
      - pympler==1.0.1
      - pyparsing==3.0.9
      - pyrsistent==0.19.3
      - python-dateutil==2.8.2
      - pytz==2022.1
      - pyyaml==6.0.1
      - pyzmq==26.2.1
      - ruptures==1.1.9
      - scienceplots==2.1.1
      - scikit-learn==1.0.2
      - scipy==1.7.3
      - seaborn==0.11.2
      - send2trash==1.8.3
      - setuptools==58.0.4
      - sip==6.6.2
      - six==1.16.0
      - sniffio==1.3.1
      - soupsieve==2.4.1
      - tabulate==0.9.0
      - terminado==0.17.1
      - threadpoolctl==3.1.0
      - tinycss2==1.2.1
      - toml==0.10.2
      - tomli==2.0.1
      - toolz==0.12.0
      - tornado==6.2
      - tqdm==4.67.1
      - traitlets==5.7.1
      - typing-extensions==4.7.1
      - wcwidth==0.2.5
      - webencodings==0.5.1
      - websocket-client==1.6.1
      - zipp==3.15.0
      - zope-interface==6.0
