name: cowera
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.7
  - eliot
  - h5py
  - jinja2
  - mdanalysis=2.0.0
  - pandas=1.3.5
  - numpy=1.21.5
  - matplotlib=3.5.1
  - mdtraj
  - pint
  - ruptures
  - scipy
  - scikit-learn
  - tabulate
  - tqdm
  - openmm=7.5.1
  - cudatoolkit=11.7
  - biopython
  - pip
  - pyyaml
  - pip:
      - scienceplots
      - deeptime
      - ipdb
